(in-package "CLOS-CONTACT")
(defclass manage-contacts (clog:clog-panel)
  (    (delete-btn :reader delete-btn)
    (update-btn :reader update-btn)
    (insert-btn :reader insert-btn)
    (next-btn :reader next-btn)
    (find-btn :reader find-btn)
    (email :reader email)
    (phone :reader phone)
    (nickname :reader nickname)
    (label-8 :reader label-8)
    (label-7 :reader label-7)
    (label-6 :reader label-6)
    (name :reader name)
    (label-4 :reader label-4)
    (contact-table :reader contact-table)
    (cc-db :reader cc-db)
))
(defun create-manage-contacts (clog-obj &key (hidden nil) (class nil) (html-id nil) (auto-place t))
  (let ((panel (change-class (clog:create-div clog-obj :content "<div style=\"box-sizing: content-box; position: static; left: 82px; top: 107px;\" id=\"CLOGB3866134949\" data-clog-name=\"cc-db\"></div><div style=\"box-sizing: content-box; position: static; left: 64px; top: 122px;\" id=\"CLOGB3866134950\" data-clog-name=\"contact-table\"></div><label for=\"\" class=\"\" style=\"box-sizing: content-box; position: absolute; left: 10px; top: 10px;\" id=\"CLOGB3866134951\" data-clog-name=\"label-4\">Name</label><input type=\"TEXT\" value=\"\" style=\"box-sizing: content-box; position: absolute; left: 140px; top: 10px;\" id=\"CLOGB3866134952\" data-clog-name=\"name\"><label for=\"\" class=\"\" style=\"box-sizing: content-box; position: absolute; left: 10px; top: 50px;\" id=\"CLOGB3866134953\" data-clog-name=\"label-6\">Nick Name</label><label for=\"\" class=\"\" style=\"box-sizing: content-box; position: absolute; left: 10px; top: 90px;\" id=\"CLOGB3866134954\" data-clog-name=\"label-7\">Phone Number</label><label for=\"\" class=\"\" style=\"box-sizing: content-box; position: absolute; left: 10px; top: 130px;\" id=\"CLOGB3866134955\" data-clog-name=\"label-8\">E-mail</label><input type=\"TEXT\" value=\"\" style=\"box-sizing: content-box; position: absolute; left: 140px; top: 50px;\" id=\"CLOGB3866134956\" data-clog-name=\"nickname\"><input type=\"TEXT\" value=\"\" style=\"box-sizing: content-box; position: absolute; left: 140px; top: 90px;\" id=\"CLOGB3866134957\" data-clog-name=\"phone\"><input type=\"TEXT\" value=\"\" style=\"box-sizing: content-box; position: absolute; left: 140px; top: 130px;\" id=\"CLOGB3866134958\" data-clog-name=\"email\"><button class=\"\" style=\"box-sizing: content-box; position: absolute; left: 15px; top: 170px; width: 55px; height: 22px; bottom: 40px;\" id=\"CLOGB3866134959\" data-clog-name=\"find-btn\">Find</button><button class=\"\" style=\"box-sizing: content-box; position: absolute; left: 90px; top: 170px; width: 55px; height: 22px; bottom: 40px;\" id=\"CLOGB3866134960\" data-clog-name=\"next-btn\">Next</button><button class=\"\" style=\"box-sizing: content-box; position: absolute; left: 165px; top: 170px; width: 55px; height: 22px; bottom: 42px;\" id=\"CLOGB3866134961\" data-clog-name=\"insert-btn\">Insert</button><button class=\"\" style=\"box-sizing: content-box; position: absolute; left: 240px; top: 170px; width: 55px; height: 22px;\" id=\"CLOGB3866134962\" data-clog-name=\"update-btn\">Update</button><button class=\"\" style=\"box-sizing: content-box; position: absolute; left: 315px; top: 170px; width: 55px; height: 22px;\" id=\"CLOGB3866134963\" data-clog-name=\"delete-btn\">Delete</button>"
         :hidden hidden :class class :html-id html-id :auto-place auto-place) 'manage-contacts)))
    (setf (slot-value panel 'delete-btn) (attach-as-child clog-obj "CLOGB3866134963" :clog-type 'CLOG:CLOG-BUTTON :new-id t))
    (setf (slot-value panel 'update-btn) (attach-as-child clog-obj "CLOGB3866134962" :clog-type 'CLOG:CLOG-BUTTON :new-id t))
    (setf (slot-value panel 'insert-btn) (attach-as-child clog-obj "CLOGB3866134961" :clog-type 'CLOG:CLOG-BUTTON :new-id t))
    (setf (slot-value panel 'next-btn) (attach-as-child clog-obj "CLOGB3866134960" :clog-type 'CLOG:CLOG-BUTTON :new-id t))
    (setf (slot-value panel 'find-btn) (attach-as-child clog-obj "CLOGB3866134959" :clog-type 'CLOG:CLOG-BUTTON :new-id t))
    (setf (slot-value panel 'email) (attach-as-child clog-obj "CLOGB3866134958" :clog-type 'CLOG:CLOG-FORM-ELEMENT :new-id t))
    (setf (slot-value panel 'phone) (attach-as-child clog-obj "CLOGB3866134957" :clog-type 'CLOG:CLOG-FORM-ELEMENT :new-id t))
    (setf (slot-value panel 'nickname) (attach-as-child clog-obj "CLOGB3866134956" :clog-type 'CLOG:CLOG-FORM-ELEMENT :new-id t))
    (setf (slot-value panel 'label-8) (attach-as-child clog-obj "CLOGB3866134955" :clog-type 'CLOG:CLOG-LABEL :new-id t))
    (setf (slot-value panel 'label-7) (attach-as-child clog-obj "CLOGB3866134954" :clog-type 'CLOG:CLOG-LABEL :new-id t))
    (setf (slot-value panel 'label-6) (attach-as-child clog-obj "CLOGB3866134953" :clog-type 'CLOG:CLOG-LABEL :new-id t))
    (setf (slot-value panel 'name) (attach-as-child clog-obj "CLOGB3866134952" :clog-type 'CLOG:CLOG-FORM-ELEMENT :new-id t))
    (setf (slot-value panel 'label-4) (attach-as-child clog-obj "CLOGB3866134951" :clog-type 'CLOG:CLOG-LABEL :new-id t))
    (setf (slot-value panel 'contact-table) (attach-as-child clog-obj "CLOGB3866134950" :clog-type 'CLOG:CLOG-ONE-ROW :new-id t))
    (setf (slot-value panel 'cc-db) (attach-as-child clog-obj "CLOGB3866134949" :clog-type 'CLOG:CLOG-DATABASE :new-id t))
    (let ((target (cc-db panel))) (declare (ignorable target)) (setf (database-connection target) (dbi:connect :sqlite3  :database-name *database*)))
    (let ((target (contact-table panel))) (declare (ignorable target)) (setf (clog-database target) (clog-database (cc-db panel)))  (setf (table-name target) "contact") (setf (where-clause target) "") (setf (order-by target) "name") (setf (limit target) "") (setf (row-id-name target) "rowid") (setf (table-columns target) '(rowid name nickname phone email)))
    (let ((target (label-4 panel))) (declare (ignorable target)) (setf (attribute target "for") (clog:js-query target "$('[data-clog-name=\\'undefined\\']').attr('id')")))
    (let ((target (label-6 panel))) (declare (ignorable target)) (setf (attribute target "for") (clog:js-query target "$('[data-clog-name=\\'undefined\\']').attr('id')")))
    (let ((target (label-7 panel))) (declare (ignorable target)) (setf (attribute target "for") (clog:js-query target "$('[data-clog-name=\\'undefined\\']').attr('id')")))
    (let ((target (label-8 panel))) (declare (ignorable target)) (setf (attribute target "for") (clog:js-query target "$('[data-clog-name=\\'undefined\\']').attr('id')")))
    (clog:set-on-click (find-btn panel) (lambda (target) (declare (ignorable target)) (manage-contacts-find target panel)))
    (clog:set-on-click (next-btn panel) (lambda (target) (declare (ignorable target)) (next-row (contact-table panel) panel)))
    (clog:set-on-click (insert-btn panel) (lambda (target) (declare (ignorable target)) (insert-row (contact-table panel) panel)))
    (clog:set-on-click (update-btn panel) (lambda (target) (declare (ignorable target)) (update-row (contact-table panel) panel)))
    (clog:set-on-click (delete-btn panel) (lambda (target) (declare (ignorable target)) (delete-row (contact-table panel) panel)))
    panel))
